version: '3.8'

services:
  user_service:
    build:
      context: ./user_service
    ports:
      - "6000:6000"
    networks:
      - microservices-net
    environment:
      DB_NAME: user_db
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: postgres_user
      DB_PORT: 5432
    depends_on:
      - postgres_user

  postgres_user:
    image: postgres:15
    restart: always
    container_name: postgres_user
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    networks:
      - microservices-net



  management_service:
    build:
      context: ./management_service
    ports:
      - "5000:5000"
    networks:
      - microservices-net
    environment:
      DB_NAME: management_db
      DB_USER: admin
      DB_PASSWORD: password
      DB_HOST: postgres_management
      DB_PORT: 5432
    depends_on:
      - postgres_management

  postgres_management:
    image: postgres:15
    container_name: postgres_management
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: management_db
    ports:
      - "5434:5432"
    networks:
      - microservices-net



  payment_service:
    build:
      context: ./payment_service
    ports:
      - "4000:4000"
    networks:
      - microservices-net
    environment:
      DB_NAME: payment_db
      DB_USER: admin
      DB_PASSWORD: password
      DB_HOST: postgres_payment
      DB_PORT: 5432
    depends_on:
      - postgres_payment

  postgres_payment:
    image: postgres:15
    container_name: postgres_payment
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payment_db
    ports:
      - "5438:5432"
    networks:
      - microservices-net



  ticket_service:
    build:
      context: ./ticket_service
    ports:
      - "3000:3000"
    networks:
      - microservices-net
    environment:
      DB_NAME: ticket_db
      DB_USER: admin
      DB_PASSWORD: password
      DB_HOST: postgres_ticket
      DB_PORT: 5432
    depends_on:
      - postgres_ticket

  postgres_ticket:
    image: postgres:15
    container_name: postgres_ticket
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ticket_db
    ports:
      - "5436:5432"
    networks:
      - microservices-net
   
   

  php_service: 
    image: php:7.4-apache 
    ports: 
      - "8080:80" 
    volumes: 
      - ./php_service:/var/www/html 
    networks: 
      - microservices-net




networks:
  microservices-net:
    driver: bridge
