apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-service
  labels:
    app: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php-container
        image: php:apache
        ports:
        - containerPort: 80
        volumeMounts:
        - name: php-volume
          mountPath: /var/www/html
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 20
      volumes:
      - name: php-volume
        persistentVolumeClaim:
          claimName: php-pvc


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  selector:
    app: php
  type:  NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
