apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: management-service
  template:
    metadata:
      labels:
        app: management-service
    spec:
      containers:
      - name: management-service
        image: casquinha2/management_service:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_NAME
          value: management_db
        - name: DB_USER
          value: admin
        - name: DB_PASSWORD
          value: password
        - name: DB_HOST
          value: postgres-management
        - name: DB_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: management-service
spec:
  selector:
    app: management-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
