apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: casquinha2/payment_service:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_NAME
          value: payment_db
        - name: DB_USER
          value: admin
        - name: DB_PASSWORD
          value: password
        - name: DB_HOST
          value: postgres-payment
        - name: DB_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer
