apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-service-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: C:/Users/Administrador/OneDrive/Desktop/projeto/php_service"  # Ensure the path contains index.php on the host
    type: Directory

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-service-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-container
        image: casquinha2/php-service:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: php-service-volume 
          mountPath: /var/www/html  # Ensure index.php is here
          
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: php-service-volume
        persistentVolumeClaim:
          claimName: php-service-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  type: NodePort
  selector:
    app: php-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31644
