apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-ticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-ticket
  template:
    metadata:
      labels:
        app: postgres-ticket
    spec:
      containers:
      - name: postgres-ticket
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: ticket_db
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-ticket
spec:
  selector:
    app: postgres-ticket
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
