apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticket-service
  template:
    metadata:
      labels:
        app: ticket-service
    spec:
      containers:
      - name: ticket-service
        image: casquinha2/ticket_service:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_NAME
          value: ticket_db
        - name: DB_USER
          value: admin
        - name: DB_PASSWORD
          value: password
        - name: DB_HOST
          value: postgres-ticket
        - name: DB_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-service
spec:
  selector:
    app: ticket-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
