apiVersion: apps/v1
kind: Deployment
metadata:
  name: interface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interface
  template:
    metadata:
      labels:
        app: interface
    spec:
      containers:
      - name: interface
        image: ialmeidaaa/interface:latest
---
apiVersion: v1
kind: Service
metadata:
  name: interface
spec:
  selector:
    app: interface
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
