apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: ialmeidaaa/user_service:latest
        ports:
        - containerPort: 6000
        env:
        - name: DB_NAME
          value: user_db
        - name: DB_USER
          value: user
        - name: DB_PASSWORD
          value: password
        - name: DB_HOST
          value: postgres-users
        - name: DB_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
  type: LoadBalancer
